# Copyright (c) 1898 & Co.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^vendor/
      - id: end-of-file-fixer
        exclude: ^vendor/
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fumpt
        args: [-w]
        exclude: ^vendor/

      - id: go-build-mod
        exclude: ^vendor/

      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: golangci-lint-config-verify
        name: golangci-lint config verify
        entry: golangci-lint config verify --config .golangci.yml
        language: system
        pass_filenames: false
        files: ^\.golangci\.yml$

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --fix
        language: system
        types: [go]
        pass_filenames: false
        exclude: ^vendor/

      - id: go-test
        name: go test
        entry: go test -race ./...
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-push]
